# Site settings
title: +z
url: 'https://throyd.github.io/' # your main domain
baseurl: 'cruzzeta/' # if you're using custom domain keep this blank example: baseurl: ''


collections:
  articles:
    collections_dir: _articles
  authors:
    collections_dir: _authors
  games:
    collections_dir: _games
    output: true
  systems:
    collections_dir: _systems
    output: true

defaults:
  - scope:
      path: ''
      type: 'games'
    values:
      layout: 'game'
  - scope:
      path: ''
      type: 'systems'
    values:
      layout: 'system'

exclude: [.scss, README.md, package.json]
